swagger: '2.0'
info:
  title: RunToBusMCP
  description: MCP Test Specification, YAML for streamable MCP support in Copilot Studio
  version: 1.0.0
host: vpj6nbw0-8000.eun1.devtunnels.ms
basePath: /
schemes:
  - https
paths:
  /mcp:
    post:
      summary: Run To Bus MCP Server
      x-ms-agentic-protocol: mcp-streamable-1.0
      operationId: InvokeMCP
      responses:
        '200':
          description: Success